### PR TITLE
use v-prefixed versions

### PR DESCRIPTION
**Pull request by fabxc**
@sdurrheimer Any other place aside from the repositories' `circle.yaml` where we need to update?

### CODE REVIEW

**Comment by sdurrheimer** [comment]
I don't think this change is necessary. The `VERSION` file doesn't already contains the `v` ?

**Comment by fabxc** [comment]
I opted not to do this as in the VERSION file the context is clear without the prefix.
Happy to hear different opinions.

**Comment by sdurrheimer** [comment]
Are we going to update the `common/version` package to automaticaly prepend the `v` in the same way here ?

**Comment by fabxc** [comment]
All occurrences there also have a clear context set (`version=%s`). To me it's mostly about image and git tags, where it's just a random chain of dots and numbers without the `v`.

**Comment by sdurrheimer** [comment]
My concerns is that `promu` and the `common/version` package are both reading the `VERSION` file.

- If we decide to auto-prepend the `v` in `promu`, we also need to do it in the `common/version`. Then this will also affects people using `promu` or the `common/version` package given that we will force them to use a `v` in their versioning strategy.
- If we add the `v` in the `VERSION` file, no need to update `promu` or the `common/version` with a auto-reprepend of the `v`. People will not be affected given that they can keep the possibility to choose to use their versioning strategy.

**Comment by fabxc** [comment]
My idea here is that the version is still just `0.3.1` for example. Just when tagging in Quay and git, we want to make known that the sequence is a version by prefixing `v`.
To me this is similar to putting `version=` in front of logging output or `version` as the label name in the `build_info` time series. It's about providing context about what the value is.

Given that `promu` is built for us only (I think we even made it explicit in the RFC that it's not a generic build tool), there is only one versioning strategy.

**Comment by sdurrheimer** [comment]
Ok but we should update our `circle.yml` files to include the `v` in both regex before merging this.

**Comment by fabxc** [comment]
For Alertmanager that's prepared for 0.3.0 – the others it becomes relevant as soon as we set the next tag afaics. So it could be done with each subsequent release as well.

**Pull request merged**
