### PR TITLE
Cobra viper to kingpin yaml refactor

### PR DESCRIPTION
**Pull request by pgier**
This builds on PR #91 and removes the dependency on Viper for managing the configuration.

### CODE REVIEW

**Comment by sdurrheimer** [comment]
@pgier Could you rebase onto master given that #91 has been merged ?

**Comment by pgier** [comment]
Ok, rebased onto master, but hold off on merging this one for a bit, I believe there is a bug.

**Comment by pgier** [comment]
Never mind, it seems to be working fine, I was just seeing the warning from issue #101

**Comment by SuperQ** [comment]
Want to rebase with the new CI docker testing?

**Comment by pgier** [comment]
The change has been rebased, I think this is ok to merge.  The travis build looks done, but I'm not sure why it's still showing as in progress.

**Comment by SuperQ** [comment]
Strange, no idea what's up with Travis.

**Comment by pgier** [comment]
@SuperQ I think it's good to merge

**Pull request merged**
