### PR TITLE
Switch to golang/dep + depedencies updates

### LINKED ISSUE #40: Update viper vendor
Update `viper` vendor to get rid of `fsnotify.v1` that is using the old `syscall` package instead of `golang.org/x/sys`.

This will probably help when crossbuilding `promu` for more platform.

### PR DESCRIPTION
**Pull request by sdurrheimer**
* Switch kardianos/govendor to golang/dep
* Update dependencies
* Use viper.SetDefault since nested keys has been fixed with spf13/viper#195

Fixes #40

### CODE REVIEW

**Comment by grobie** [comment]
I'm generally fine with switching from govendor to dep, but this should be discussed first. I believe we should strive for similar tooling in all of our golang projects in the prometheus org.

Also given Gopkg.lock, we could decide to stop actually vendoring projects.

**Comment by sdurrheimer** [comment]
> I'm generally fine with switching from govendor to dep, but this should be discussed first.

Sure, that one of the reason I opened a PR = )

**Comment by grobie** [comment]
Kick-off the discussion with an email to prometheus-developers@ please.

**Comment by SuperQ** [comment]
Apparently `dep` is now deprecated.

**Comment by sdurrheimer** [comment]
Is it ? I thought they would continue to maintain it alongside Golang 1.11 modules.

**Comment by SuperQ** [comment]
It will still be there, but I'd rather not jump from govendor to dep, just to have to switch again.

**Comment by SuperQ** [comment]
Closing in favor of https://github.com/prometheus/promu/pull/117.

**Pull request closed without merging**
