### PR TITLE
Use common/version + build process

### PR DESCRIPTION
**Pull request by sdurrheimer**
Pros:
- Consistent with others projects

Cons:
- Using `common/version` for `promu` has some drawbacks, it adds a lot of vendoring.
- Maybe weird to use `promu` to build `promu`

---
This change is [Reviewable](https://reviewable.io/reviews/prometheus/promu/36)

### CODE REVIEW

**Comment by fabxc** [comment]
I think it's fine to make promu build itself. Sort of what compilers like to do :)

Don't worry about dependencies. That's why we have vendoring. To me it only feels wrong if there's a really huge number of transitive dependencies, i.e. the Kubernetes client.

**Comment by 7heo** [comment]
I hope that leaving a comment in here is acceptable for non-contributors. Since promu is a dependency to build prometheus, it would be really advantageous to have it released too (so we can also package it). Checking the vendor dependencies in git is a solution, but it is heavy and hardly practical, I would recommend to use of glide for this, like so:

```
$ glide init --non-interactive
$ glide update
```

And then it would be best to fix the dependencies to a specific version, so to have reproducible builds.

I write this suggestion because I think that it is a good solution, perfectly adapted at this step of the project.

**Comment by sdurrheimer** [comment]
The purpose of this PR is to set up the same build process as others prometheus repos for releases.
So `promu` will definitely be released too.

I have no experience with `glide`. The thing is we use `govendor` as a vendoring manager for all our golang repos so, I don't really want to use a different one for `promu`.

**Comment by fabxc** [comment]
Yes, let's stick with govendor. If we ever need features glide provide, we
can switch all repos at once.

**Comment by 7heo** [comment]
I get the point, and I agree that changes should be as atomic as they can be. However, I would believe that this project is small enough to be a perfect candidate for trying glide before using it on all projects, should that ever happen.

**Comment by juliusv** [comment]
> Checking the vendor dependencies in git is a solution, but it is heavy and hardly practical

That's the usual way to go with Go. Also, vendoring dependencies is the only way to be sure that you can still get a particular version of a dependency at build time, since things might disappear or be unreachable.

**Comment by 7heo** [comment]
I am not really convinced by the "usual way" arguments. But it is true that the availability of dependencies at build time is a problem, with go. However isn't what `go fix` is supposed to fix exactly?

**Comment by juliusv** [comment]
No, as far as I know, `go fix` just helps you migrate between Go versions.

No tool that doesn't vendor (i.e. make a copy) somehow can protect you from dependencies disappearing completely, or GitHub just being down when you urgently need to build&deploy a new version.

**Comment by 7heo** [comment]
So in other words, go encourages the redundency and copy/pasting of code? That does not sound like a sane design to me. Is there a way to include dependencies from inherently redundant sources so we don't have such a problem?

**Comment by sdurrheimer** [comment]
Ready for review

**Comment by fabxc** [comment]
LGTM 👍

**Pull request merged**
