### PR TITLE
Cobra to kingpin refactor

### PR DESCRIPTION
**Pull request by pgier**
First attempt at refactoring the CLI parsing from cobra to kingpin to match the rest of the prometheus projects.  Probably still needs a bit more testing before merging, but it seems to work for me.
Kingpin seems to simplify the CLI config (~50 fewer SLOC), however the Viper integration seems more awkward now with Kingpin and could maybe be improved.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Why are we using two flag libraries?

**Comment by pgier** [comment]
This removes cobra and uses kingpin instead, so it's still only one flag library.  If you are referring to Viper, it's used for loading the config file.

**Comment by SuperQ** [comment]
I'd like to move forward with this, so we can get this onto kingpin. This would make it match the rest of the Prometheus project.

@pgier Would you please rebase this to fix the conflicts?

**Comment by sdurrheimer** [comment]
@SuperQ We should probably cut a release before switching to kingpin, don't you think ?

**Comment by sdurrheimer** [comment]
@pgier Could you update the Usage section in the README to match the new Kingpin output ?

**Pull request merged**
