### PR TITLE
Parallel cross building

### PR DESCRIPTION
**Pull request by sylr**
Attempt at https://github.com/prometheus/promu/issues/176

### CODE REVIEW

**Comment by simonpasquier** [comment]
Thanks for looking at this! See https://github.com/prometheus/promu/issues/176#issuecomment-586230373, I'm working on something that would enable the improvements I've described there.

**Comment by grobie** [comment]
Any update here @simonpasquier?

**Comment by SuperQ** [comment]
Is there any interest in resuming work on this?

**Comment by sylr** [comment]
Not from my end, anyone is welcome to takeover from where I left it if interested.

**Comment by SuperQ** [comment]
Closing in favor of https://github.com/prometheus/promu/pull/208.

**Pull request closed without merging**
