### PR TITLE
add functionality to optionally build one or more binary from promu.yml

### PR DESCRIPTION
**Pull request by cstyan**
While working in `prometheus/prometheus` I wanted to be able to run `make build` and only build `promtool` instead of both `promtool` and `prometheus`. Rather than commenting out one of the binaries in the yaml file every time, I made some changes to promu to allow for a comma separated string of binary names to be passed to the `build` command.

Building a single binary looks like this:
```$make build BINARIES=promtool
>> fetching promu
>> building binaries
 >   promtool
```

Building all looks like this:
```
$make build                  
>> fetching promu
>> building binaries
 >   prometheus
 >   promtool
```
or this:
```
$make build BINARIES=all     
>> fetching promu
>> building binaries
 >   prometheus
 >   promtool
```

And trying to build a binary that is not present in your yaml file:
```$make build BINARIES=test
>> fetching promu
>> building binaries
!! validation of given binary names for build command failed: binary test not found in config

Makefile:57: recipe for target 'build' failed
make: *** [build] Error 1```

### CODE REVIEW

**Comment by sdurrheimer** [comment]
@cstyan Can you rebase against master ?

**Comment by cstyan** [comment]
@sdurrheimer done :)

**Comment by carlpett** [comment]
Was this intentionally backwards incompatible? Our builds started failing in wmi_exporter since we do not set build.binaries, maybe that has been required previously but not enforced?

**Comment by sdurrheimer** [comment]
@carlpett No, it should have been backward compatible. I will take a look.

**Comment by carlpett** [comment]
Hm, just adding `build.binaries` did not fix it for us. We have been building with `promu build -v .`, and it was trying to find the binary `.`. Removing the dot fixes it.

**Comment by sdurrheimer** [comment]
@carlpett yeah, the `.` was useless before. Now it is used to build a selected binary.

**Comment by cstyan** [comment]
I certainly didn't intend for this to not be backwards compatible! :(  

Sounds like treating `.` as `all` may be the fix we're looking for? @sdurrheimer

**Comment by grobie** [comment]
`promu build` did not take any arguments before, so this change was not backwards incompatible. It can not be expected that relying on an unspecified side effect is forward compatible.

**Pull request merged**
