### PR TITLE
Drop support for Go 1.5

### PR DESCRIPTION
**Pull request by sdurrheimer**
@AlekSi

### CODE REVIEW

**Comment by AlekSi** [comment]
Do you still support 1.5? You don't test with this version in Travis CI.

**Comment by sdurrheimer** [comment]
There is difference between using `promu` which a golang 1.5 environment and testing compiling `promu` itself on golang 1.5.

We do support `promu` usage on 1.5, or more precisely, we didn't drop the support so it should work as before.

**Comment by AlekSi** [comment]
Then maybe it's a good time to drop 1.5 support? That will simplify other code too (GO15VENDOREXPERIMENT).

**Comment by sdurrheimer** [comment]
@grobie what do you think about dropping 1.5 support ?

**Comment by grobie** [comment]
Let's go for it. We only use 1.8 and soon 1.9 these days.

**Comment by AlekSi** [comment]
Bonus point: you can get rid of `GO15VENDOREXPERIMENT` everywhere.

**Comment by sdurrheimer** [comment]
Updated

**Pull request merged**
