### PR TITLE
Add linux/riscv64 to default platforms

### PR DESCRIPTION
**Pull request by der-eismann**
With the rising number of RISC-V boards like the [STAR64](https://9to5linux.com/star64-is-now-available-to-order-as-pine64s-first-risc-v-sbc) or the [SiFive boards](https://www.sifive.com/press/sifive-partners-with-intel-to-spark-innovation-in-high-performance), having builds for `linux/riscv64` is becoming more important. Support for it has been in Go for a while and should be mature at this point.

### CODE REVIEW

**Comment by SuperQ** [comment]
Hmm, weird, CircleCI didn't run. Going to try and close/open this.

**Review by SuperQ — APPROVED** [review]
LGTM

**Review by dongjiang1989 — APPROVED** [review]
LGTM

**Comment by dongjiang1989** [comment]
Thanks for contributing code!   https://github.com/prometheus/node_exporter/pull/2706 requires this feature

**Comment by SuperQ** [comment]
Hmm, that didn't re-trigger the CI.

**Comment by dongjiang1989** [comment]
great！

**Pull request merged**
