### PR TITLE
Add Apple Silicon and Illumos

### LINKED ISSUE #191: would like cross built promu binaries for GOOS=illumos GOARCH=amd64
The Prometheus build attempts to download a prebuilt `promu` binary from GitHub.  The software builds and works on illumos/amd64 systems today, but obviously is not currently being built as part of the official CI/CD pipeline or published in the releases.

Can we get illumos binaries added to the releases please?  I am happy to be a point of contact in future if any build issues arise.  If I should file a PR, I'd appreciate it if you could point me in the right direction so I can make the right change!

Thanks!

### LINKED ISSUE #199: darwin/arm64 (Apple Silicon M1) support
Hi,

I wanted to ask if there any plans to build binaries for `darwin/arm64` to support running `node_exporter` natively on MacOS machines running M1 processors?

This would require updating to Go 1.16 also I believe as that's when support for that arch was added.

We currently have the following version of `node_exporter` running:
```
node_exporter, version 1.1.1 (branch: , revision: )
  build user:       Homebrew
  build date:
  go version:       go1.15.7
  platform:         darwin/amd64
```

We are running it under [Rosetta](https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment) on MacOS 11.0.1 but there are known issues with earlier versions of Rosetta and Go (https://github.com/golang/go/issues/42700) that I believe we are also seeing. Supposedly they are fixed in later versions of Rosetta but I'd prefer if we could run it natively regardless.

I'm not that familiar with the code base but I'm happy to help with implementing/testing if I can. I had a quick look and can see there's various files where 1.15 is mentioned and the darwin builds seem to be in `.promu-cgo.yml`.

Thanks

### PR DESCRIPTION
**Pull request by roidelapluie**
Closes #199
Closes #191

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by SuperQ** [comment]
Want to do https://github.com/prometheus/promu/pull/202 first?

**Comment by roidelapluie** [comment]
It's done

**Review by SuperQ — APPROVED** [review]
LGTM

**Comment by jclulow** [comment]
Hello!  Pardon what may be a silly question, but with this change should we see illumos or Apple Silicon binaries in the assets for the 0.8.0 release?

I can't seem to find either one here: https://github.com/prometheus/promu/releases/tag/v0.8.0

**Comment by matthiasr** [comment]
The 0.8.0 release was [built by promu 0.6.0](https://github.com/prometheus/promu/blob/v0.8.0/Makefile.common#L81), we will need to update Makefile.common (to my shame I don't know which repository is the source of truth for that)

**Comment by roidelapluie** [comment]
Prometheus/Prometheus. but promtool should build from itself. I have the code on my laptop.

**Comment by SuperQ** [comment]
Makefile.common comes from prometheus/prometheus.

**Pull request merged**
