### PR TITLE
Fallback to git describe output if no VERSION files provided

### PR DESCRIPTION
**Pull request by sylr**
Signed-off-by: Sylvain Rabot <s.rabot@lectra.com>

### CODE REVIEW

**Comment by pgier** [comment]
lgtm!

**Comment by SuperQ** [comment]
I don't see a linked issue, what's the use case for this?

**Comment by sylr** [comment]
No there is no issue, I made this quickly because on Thanos after a tagged version they append '-master' to the tag in the VERSION file and I thought removing this file completely and using git describe as input for the Version in the build would be more meaningful.

**Comment by sylr** [comment]
What do you think @SuperQ  ?

**Comment by SuperQ** [comment]
I'm not sure this makes sense for promu. I guess we haven't really specified the intended behavior here.

**Comment by carlpett** [comment]
FWIW this is how I've done automation on all projects where I've used promu (although as part of the build steps rather than inside promu itself). For the workflows where I've been involved, checking in the VERSION file doesn't really fit in, and has resulted in wrong versions being written in due to forgetting to bump the file.

**Comment by SuperQ** [comment]
The consensus on prometheus-developers says yes.

**Pull request merged**
